food/urls.py
from django.urls import path
from . import views
app_name = 'food'

urlpatterns = [
    # path('', views.index, name ='index'),
    path('', views.IndexClassView.as_view(), name ='index'),
    # path('<int:item_id>', views.detail, name ='detail'),
    path('<int:pk>', views.FoodDetail.as_view(), name ='detail'),
    # path('add/', views.create_item, name ='create_item'),
    path('add/', views.CreateItem.as_view(), name ='create_item'),
    path('update/<int:id>/',views.update_item,name='update_item'),
    path('delete/<int:id>/',views.delete_item,name='delete_item'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as authentication_views
from django.conf import settings
from django.conf.urls.static import static

from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('food.urls')),
    path('register/',user_views.register,name='register'),
    path('login/', authentication_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', authentication_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/',user_views.profilepage,name='profile'),
        url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
]



urlpatterns += [] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Item(models.Model):


    def __str__(self):
        return self.item_name
    user_name = models.ForeignKey(User,on_delete=models.CASCADE,default=1)
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=1000,default="https://www.netclipart.com/pp/m/219-2197077_wedding-dinner-icons.png")

    def get_absolute_url(self):
         return reverse("food:detail", kwargs={"pk": self.pk})

users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    image = models.ImageField(default='profilepic.jpg', upload_to='profile_pictures')
    location = models.CharField(max_length=100 )
def __str__(self):
    return self.user.username

food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name','item_desc','item_price','item_image']

users/forms.py
from django import forms
from django.contrib.auth.models import  User
from django.contrib.auth.forms import UserCreationForm


class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username','email', 'password1','password2']

food/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Item
from django.template import loader
from .forms import ItemForm
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView

# def  index(request):
#     item_lists = Item.objects.all()
#     template = loader.get_template('food/index.html')
#     context= {
#         'item_list':item_lists,

#     }
#     return render(request, 'food/index.html', context)
    # return HttpResponse(template.render(context, request))
class IndexClassView(ListView):
    model = Item
    template_name ='food/index.html'
    context_object_name ='item_list'

# def detail(request, item_id):
#     item = Item.objects.get(pk=item_id)
#     context = {
#         'item':item,
#     }
#  return render(request, 'food/detail.html', context)

class FoodDetail(DetailView):
    model = Item
    template_name = 'food/detail.html'

   
# def create_item(request):
#     form = ItemForm(request.POST or None)
#     if form.is_valid():
#         form.save()
#         return redirect('food:index')
#     return render(request, 'food/item-form.html', {'form':form})
class CreateItem(CreateView):
    model = Item
    fields = ['item_name','item_desc','item_price','item_image']
    template_name='food/item-form.html'

    def form_valid(self,form):
        form.instance.user_name = self.request.user

        return super().form_valid(form)
      

def update_item(request,id):
    item = Item.objects.get(id=id)
    form = ItemForm(request.POST or None, instance=item)

    if form.is_valid():
        form.save()
        return redirect('food:index')

    return render(request,'food/item-form.html',{'form':form,'item':item})
def delete_item(request,id):
    item = Item.objects.get(id=id)

    if request.method == 'POST':
        item.delete()
        return redirect('food:index')

    return render(request,'food/item-delete.html',{'item':item})

users/views.py
from django.shortcuts import redirect,render
from django.contrib import messages
from django.contrib.auth.decorators import login_required 
from .forms import RegisterForm

def register(request):
    if request.method=='POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f' welcome {username}, account has created')
            return redirect('login')
    else:
       form = RegisterForm()
    return render(request, 'users/register.html', {'form':form})
@login_required
def profilepage(request):

    return render(request, 'users/profile.html')

food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Food</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
</head>
<body>


    <!-- As a link -->
    
<nav class="navbar navbar-expand-sm bg-light navbar-dark>
      <a class="navbar-brand" href="#">Food Shop</a>
         <ul class="nav navbar-nav mr-auto">  
          </ul>
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'food:create_item' %}">Add Item</a>
        </li>
           {% if user.is_authenticated %}
                       <li class="nav-item"> 
                       <a href="{% url 'logout' %}" class="nav-link">Logout</a>
                         </li>
                         <li class="nav-item">
                        <a href="{% url 'profile' %}" class="nav-link ">Profile</a>
                        </li>
                    {% else %}
                     <li class="nav-item"> 
                        <a href="{% url 'login' %}" class="nav-link ">Login</a>
                      </li>
                      <li class="nav-item"> 
                        <a href="{% url 'register' %}" class="nav-link ">Sign up</a>
                      </li>
                    {% endif %}



       </ul>
  </nav>
  {% if messages %}
      {% for message in messages %}
       <div class="alert alert-{{ message.tags}}">{{message}}</div>
           
      {% endfor %}
    {% endif %}

{% block body %}


{% endblock %}
  </body>
  </html>

food/templates/food/detail.html
{% extends "food/base.html" %}


{% block body %}

<div class="container">
    <div class="row m-5">
        <div class="col-md-6">
            <img height="300px"  width="300" src="{{item.item_image}}" class="card"/>
        </div>

        <div class="col-md-6">
            {% comment %} <h1>{{item.item_name}}</h1>
            <h2>{{item.item_desc}}</h2>
            <h3>{{item.item_price}}</h3>   {% endcomment %}
            <h1>{{object.item_name}}</h1>
            <h2>{{object.item_desc}}</h2>
            <h3>{{object.item_price}}</h3> 
            <a class="btn btn-danger" href="{% url 'food:delete_item' item.id %}">Delete</a>
           
        </div>
    </div>
</div>
{% endblock %}    

food/templates/food/index.html
{% extends "food/base.html" %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Food</title>
    
</head>
<body>
    <!-- As a link -->

    {% block body %}
  {%  for item in item_list %}
  <div class="row m-5">
    <div class="col-md-3 offset-md-2">
        <img class="card" height="150px" width="150px" src="{{item.item_image}}"/>
    </div>
    <div class="col-md-4">
        <h3>{{item.item_name}}</h3>
        <h5>{{item.item_desc}}</h5>
        <h5>${{item.item_price}}</h5>
        Added By:<h6>{{item.user_name}}</h6>
        <!--delete this later-->
        
        <!---->
    </div>
    <div class="col-md-2">
        <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>
    </div>
</div>
<div class="row">
    <div class="offset-md-2 col-md-8">
        <hr>
    </div>
</div>


  {% endfor %}

  {% endblock %}


this is an old code 
  <ul>
      <a href="{% url 'food:detail'  item.id %}"><li>  -- {{item.item_name}}</li></a>
      
  </ul>



 
</body>
</html>

food/templates/food/item-delete.html
{% extends 'food/base.html' %} 
{% block body %}

<form method="POST"">
    {% csrf_token %}
    <h2>Are you sure you want to delete{{item.item_name}}</h2>
    <button type="submit">Confirm</button>
</form>

{% endblock %}

food/templates/food/item-form.html
{% extends 'food/base.html' %} 

{% block body %}
<div class="container mt-1">
   <div class="row">
       <div class="col-md-4 offset-md-4">
       <div class="card">
         <div class="card-header bg-info">
             <div class="card-title">
             Add Item
             </div>
             </div>
             <div class="card-body">
             <form method="POST">
         {% csrf_token %}
          {% for field in form %}
          <div class="form-group">
           {{ field.name }}
           {{field}}
          </div>

          {% endfor %}
         <button class="btn-info" type="submit">save</button>
    </form>
             </div>
        
       </div>
    </div>

</div>


{% endblock %}
 

users/templates/users/login.html
{% extends 'food/base.html' %} 

{% block body %}
<div class="container mt-1">
   <div class="row">
       <div class="col-md-4 offset-md-4">
       <div class="card">
         <div class="card-header">
             <div class="card-title">
             Login
             </div>
             </div>
             <div class="card-body">
             <form method="POST">
         {% csrf_token %}
          {% for field in form %}
          <div class="form-group">
           {{ field.name }}
           {{field}}
          </div>

          {% endfor %}
         <button class="btn-info" type="submit">Login</button>
    </form>
             </div>
        
       </div>
    </div>

</div>


{% endblock %}
 

users/templates/users/logout.html
<h1>You have been logged out</h1>

users/templates/users/profile.html
<h1>{{user.username}}</h1>
<img src="{{user.profile.image.url}}" width="150px" height="150px">

users/templates/users/register.html
{% extends 'food/base.html' %} 

{% block body %}
<div class="container mt-1">
   <div class="row">
       <div class="col-md-4 offset-md-4">
       <div class="card">
         <div class="card-header bg-info">
             <div class="card-title">
             Register
             </div>
             </div>
             <div class="card-body">
             <form method="POST">
         {% csrf_token %}
          {% for field in form %}
          <div class="form-group">
           {{ field.name }}
           <br>
           {{field}}
          </div>

          {% endfor %}
         <button class="btn-info" type="submit">Login</button>
    </form>
             </div>
        
       </div>
    </div>

</div>


{% endblock %}
 